//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaAccountLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaAccountLeave()
        {
            this.TaLeaves = new HashSet<TaLeave>();
        }
    
        public int CoId { get; set; }
        public string CoUserID { get; set; }
        public string CoLeaveType { get; set; }
        public Nullable<int> CoYear { get; set; }
        public Nullable<System.DateTime> CoCreated { get; set; }
        public Nullable<System.DateTime> CoUpdated { get; set; }
        public Nullable<decimal> CoOpening { get; set; }
        public Nullable<decimal> CoCredited { get; set; }
        public Nullable<decimal> CoAvailed { get; set; }
        public Nullable<decimal> CoApplied { get; set; }
        public Nullable<decimal> coApproved { get; set; }
        public Nullable<decimal> CoBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaLeave> TaLeaves { get; set; }
    }
}
