//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaLeave
    {
        public int CoId { get; set; }
        public Nullable<int> CoLeaveAccountId { get; set; }
        public string CoUserID { get; set; }
        public Nullable<System.DateTime> CoStartdate { get; set; }
        public Nullable<System.DateTime> CoEndDate { get; set; }
        public Nullable<System.DateTime> CoApplydate { get; set; }
        public string coReason { get; set; }
        public string CoStatus { get; set; }
    
        public virtual TaAccountLeave TaAccountLeave { get; set; }
    }
}
