//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDayEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaLogin
    {
        public int CoId { get; set; }
        public string CoLoginName { get; set; }
        public string CologinPassword { get; set; }
        public Nullable<System.DateTime> CoCreated { get; set; }
        public Nullable<System.DateTime> CoUpdated { get; set; }
        public string CoRole { get; set; }
    }
}
